export type InstitutionalRuleSummary = {
  number: number;
  title: string;
  simpleExplanation: string;
  mainConcepts: string[];
  keyPoints: string[];
  commonMistakes: string[];
  quickSummary: string;
};

export const institutionalRules: InstitutionalRuleSummary[] = [
  {
    number: 1,
    title: "El terreno de juego",
    simpleExplanation: "Define dimensiones, lineas, areas, arcos y condiciones basicas del campo.",
    mainConcepts: ["Lineas del campo", "Areas", "Arcos", "Marcaciones"],
    keyPoints: ["Las lineas forman parte del area que delimitan.", "El arbitro controla si el campo es apto."],
    commonMistakes: ["Creer que una pelota sobre la linea esta fuera.", "No revisar redes o marcaciones antes del inicio."],
    quickSummary: "La Regla 1 ordena el escenario donde se juega el partido.",
  },
  {
    number: 2,
    title: "El balon",
    simpleExplanation: "Establece condiciones del balon: forma, presion, reemplazo y autorizacion arbitral.",
    mainConcepts: ["Balon apto", "Reemplazo", "Autorizacion"],
    keyPoints: ["Si el balon queda defectuoso, el arbitro decide como reanudar.", "No se cambia sin autorizacion."],
    commonMistakes: ["Reanudar automaticamente sin analizar cuando se dana.", "Aceptar cualquier balon sin control previo."],
    quickSummary: "El balon debe ser seguro, reglamentario y controlado por el arbitro.",
  },
  {
    number: 3,
    title: "Los jugadores",
    simpleExplanation: "Regula cantidad de jugadores, sustituciones, jugadores extra y procedimientos.",
    mainConcepts: ["Cantidad minima", "Sustituciones", "Jugador extra", "Procedimiento"],
    keyPoints: ["Un partido no continua si un equipo queda con menos jugadores que el minimo permitido.", "La sustitucion requiere procedimiento correcto."],
    commonMistakes: ["Permitir ingreso sin autorizacion.", "No controlar reemplazos simultaneos."],
    quickSummary: "Ordena quien puede jugar y como se realizan los cambios.",
  },
  {
    number: 4,
    title: "El equipamiento",
    simpleExplanation: "Indica la indumentaria obligatoria y los elementos peligrosos o no permitidos.",
    mainConcepts: ["Seguridad", "Camiseta", "Canilleras", "Colores"],
    keyPoints: ["La seguridad es prioritaria.", "El arbitro puede ordenar retirar elementos peligrosos."],
    commonMistakes: ["Permitir joyas tapadas.", "No diferenciar colores similares entre equipos o arqueros."],
    quickSummary: "El equipamiento debe identificar y proteger a los jugadores.",
  },
  {
    number: 5,
    title: "El arbitro",
    simpleExplanation: "Describe autoridad, decisiones, control disciplinario y responsabilidades del arbitro.",
    mainConcepts: ["Autoridad", "Decision", "Disciplina", "Seguridad"],
    keyPoints: ["Sus decisiones de hecho son definitivas.", "Debe proteger la integridad del partido."],
    commonMistakes: ["No comunicar claramente.", "Perder control preventivo por falta de presencia."],
    quickSummary: "El arbitro dirige el partido y sostiene el control reglamentario.",
  },
  {
    number: 6,
    title: "Otros miembros del equipo arbitral",
    simpleExplanation: "Ordena funciones de asistentes, cuarto arbitro, VAR y otros oficiales cuando existan.",
    mainConcepts: ["Asistentes", "Colaboracion", "Comunicacion", "VAR"],
    keyPoints: ["El equipo arbitral asiste al arbitro principal.", "La comunicacion debe ser clara y oportuna."],
    commonMistakes: ["Senalizar tarde.", "No coordinar antes del partido criterios de colaboracion."],
    quickSummary: "La tarea arbitral es colectiva, aunque la decision final sea del arbitro.",
  },
  {
    number: 7,
    title: "La duracion del partido",
    simpleExplanation: "Define tiempos de juego, adicion, descanso y recuperacion de tiempo perdido.",
    mainConcepts: ["Tiempo reglamentario", "Adicion", "Descanso", "Interrupciones"],
    keyPoints: ["El arbitro recupera tiempo perdido.", "La adicion debe responder a interrupciones reales."],
    commonMistakes: ["Adicionar sin criterio.", "No contabilizar sustituciones, lesiones o demoras claras."],
    quickSummary: "Controla cuanto se juega y como se recupera el tiempo perdido.",
  },
  {
    number: 8,
    title: "Inicio y reanudacion del juego",
    simpleExplanation: "Explica saque inicial, balon a tierra y otras reanudaciones generales.",
    mainConcepts: ["Saque inicial", "Balon a tierra", "Procedimiento"],
    keyPoints: ["Cada reanudacion tiene lugar, ejecutor y condiciones.", "El arbitro debe controlar la distancia y el procedimiento."],
    commonMistakes: ["Confundir balon a tierra con tiro libre.", "Permitir reanudaciones sin senal o lugar correcto."],
    quickSummary: "Define como empieza y como vuelve a ponerse en juego la pelota.",
  },
  {
    number: 9,
    title: "Balon en juego y fuera de juego",
    simpleExplanation: "Indica cuando el balon esta dentro o fuera del juego.",
    mainConcepts: ["Lineas", "Salida total", "Juego activo"],
    keyPoints: ["El balon debe cruzar completamente la linea para estar fuera.", "Rebotes en arbitro o postes no siempre detienen el juego."],
    commonMistakes: ["Cobrar salida cuando solo una parte del balon supera la linea.", "No observar la totalidad del balon."],
    quickSummary: "El balon sigue en juego salvo que salga completamente o el arbitro detenga.",
  },
  {
    number: 10,
    title: "Resultado del partido",
    simpleExplanation: "Define gol valido, ganador y procedimientos para determinar resultado.",
    mainConcepts: ["Gol", "Linea de meta", "Definicion", "Penales"],
    keyPoints: ["El balon debe cruzar completamente la linea de meta.", "Un gol requiere que no exista infraccion previa sancionable."],
    commonMistakes: ["Validar sin comprobar infraccion previa.", "Confundir pelota sobre linea con gol."],
    quickSummary: "Ordena como se marca un gol y como se define el resultado.",
  },
  {
    number: 11,
    title: "Fuera de juego",
    simpleExplanation: "Explica posicion, participacion activa, interferencia y obtencion de ventaja.",
    mainConcepts: ["Posicion", "Interferencia", "Ventaja", "Momento del pase"],
    keyPoints: ["Estar en posicion no es infraccion por si solo.", "La infraccion depende de participar activamente."],
    commonMistakes: ["Cobrar solo por posicion.", "No esperar participacion clara del atacante."],
    quickSummary: "Fuera de juego exige posicion y participacion activa.",
  },
  {
    number: 12,
    title: "Faltas y conducta incorrecta",
    simpleExplanation: "Regula infracciones, disciplina, manos, faltas tacticas y tarjetas.",
    mainConcepts: ["Falta", "Mano", "Disciplina", "Faltas tacticas"],
    keyPoints: ["La sancion depende de accion, intensidad, consecuencia y contexto.", "SPA y DOGSO se trabajan dentro de faltas tacticas."],
    commonMistakes: ["Cobrar contacto leve como falta.", "Separar SPA/DOGSO del analisis tactico general."],
    quickSummary: "Es la regla central para decidir faltas, manos y disciplina.",
  },
  {
    number: 13,
    title: "Tiros libres",
    simpleExplanation: "Define tiros libres directos e indirectos, senalizacion, distancia y ejecucion.",
    mainConcepts: ["Directo", "Indirecto", "Distancia", "Lugar"],
    keyPoints: ["El indirecto requiere senal del arbitro.", "La barrera debe respetar distancia reglamentaria."],
    commonMistakes: ["No levantar brazo en indirecto.", "Permitir ejecucion desde lugar incorrecto."],
    quickSummary: "Ordena como se reanuda despues de muchas infracciones.",
  },
  {
    number: 14,
    title: "El penal",
    simpleExplanation: "Regula procedimiento, posicion de jugadores, arquero, ejecutor e infracciones.",
    mainConcepts: ["Ejecutor", "Arquero", "Area penal", "Infracciones"],
    keyPoints: ["El arquero debe respetar condiciones del procedimiento.", "La invasion se evalua segun impacto."],
    commonMistakes: ["Repetir siempre por cualquier ingreso.", "No identificar quien infringe primero."],
    quickSummary: "El penal tiene procedimiento estricto y consecuencias claras.",
  },
  {
    number: 15,
    title: "Saque de banda",
    simpleExplanation: "Indica cuando corresponde, desde donde y como debe ejecutarse.",
    mainConcepts: ["Lugar", "Ejecucion", "Pies", "Manos"],
    keyPoints: ["El ejecutor debe usar ambas manos y lanzar desde atras y por encima de la cabeza.", "Se realiza desde donde salio el balon."],
    commonMistakes: ["Permitir ejecucion muy lejos del punto.", "No controlar pies sobre o fuera de la linea."],
    quickSummary: "Reanuda cuando el balon sale por linea de banda.",
  },
  {
    number: 16,
    title: "Saque de meta",
    simpleExplanation: "Define cuando se concede y como se ejecuta desde el area de meta.",
    mainConcepts: ["Area de meta", "Balon en juego", "Rivales", "Procedimiento"],
    keyPoints: ["El balon esta en juego cuando es pateado y se mueve claramente.", "Los rivales deben respetar el procedimiento."],
    commonMistakes: ["Exigir que salga del area penal con reglas antiguas.", "No controlar presion temprana de rivales."],
    quickSummary: "Reanuda cuando el ataque envia el balon fuera por linea de meta sin gol.",
  },
  {
    number: 17,
    title: "Tiro de esquina",
    simpleExplanation: "Regula cuando corresponde y como se ejecuta desde el cuadrante de esquina.",
    mainConcepts: ["Cuadrante", "Distancia", "Ejecucion", "Balon en juego"],
    keyPoints: ["El balon debe estar en el cuadrante.", "Los rivales respetan distancia reglamentaria."],
    commonMistakes: ["Permitir balon fuera del cuadrante.", "No controlar distancia de defensores."],
    quickSummary: "Reanuda cuando la defensa envia el balon fuera por su propia linea de meta.",
  },
];
