export type RuleQuestion = {
  id: number;
  question: string;
  options: string[];
  correct: number;
  topic: string;
  lawReference: string;
  difficulty: "Media" | "Avanzada";
  explanation: string;
  ifabExplanation: string;
};

export const rulesQuestions: RuleQuestion[] = [
  {
    id: 1,
    topic: "Regla 1",
    lawReference: "Regla 1 - El terreno de juego",
    difficulty: "Media",
    question: "Durante el partido se rompe el travesano y no puede repararse ni reemplazarse de forma segura. ¿Cómo debe proceder el árbitro?",
    options: ["Reemplazarlo con una cuerda", "Continuar si ambos capitanes aceptan", "Suspender definitivamente el partido", "Jugar sin travesano hasta el descanso"],
    correct: 2,
    explanation: "El partido no puede continuar sin un travesano reglamentario y seguro.",
    ifabExplanation: "La Regla 1 exige que el travesano sea reparado o sustituido. Una cuerda o material flexible no puede reemplazarlo; si no hay solución reglamentaria, el partido debe suspenderse definitivamente.",
  },
  {
    id: 2,
    topic: "Regla 1",
    lawReference: "Regla 1 - El terreno de juego",
    difficulty: "Avanzada",
    question: "Un jugador realiza deliberadamente una marca no autorizada sobre el terreno durante el juego. ¿Qué decisión corresponde en la siguiente interrupción?",
    options: ["Solo borrar la marca", "Amonestar por conducta antideportiva", "Expulsar por conducta violenta", "Advertir verbalmente sin tarjeta"],
    correct: 1,
    explanation: "Realizar marcas no autorizadas es conducta antideportiva.",
    ifabExplanation: "La Regla 1 prohíbe que los jugadores realicen marcas no autorizadas en el terreno. El infractor debe ser amonestado por conducta antideportiva cuando el árbitro pueda aplicar la sanción.",
  },
  {
    id: 3,
    topic: "Regla 2",
    lawReference: "Regla 2 - El balón",
    difficulty: "Media",
    question: "El balón se vuelve defectuoso mientras está en juego, sin que se haya producido una infracción. ¿Cómo se reanuda?",
    options: ["Tiro libre indirecto", "Balón a tierra", "Saque de banda", "Se repite la última reanudación"],
    correct: 1,
    explanation: "Se detiene el juego y se reemplaza el balón.",
    ifabExplanation: "Según la Regla 2, si el balón se vuelve defectuoso durante el juego, el árbitro detiene el partido y lo reanuda con balón a tierra usando un balón reglamentario.",
  },
  {
    id: 4,
    topic: "Regla 2",
    lawReference: "Regla 2 - El balón",
    difficulty: "Avanzada",
    question: "En un penal, el balón se mueve hacia delante pero se vuelve defectuoso antes de tocar a otro jugador, los postes o el travesano. ¿Qué corresponde?",
    options: ["Balón a tierra", "Saque de meta", "Repetir el penal", "Tiro libre indirecto"],
    correct: 2,
    explanation: "El penal debe repetirse.",
    ifabExplanation: "La Regla 2 establece una excepción específica: si el balón se vuelve defectuoso durante un penal o una tanda mientras avanza y antes de tocar jugador o marco, el lanzamiento se repite.",
  },
  {
    id: 5,
    topic: "Regla 3",
    lawReference: "Regla 3 - Los jugadores",
    difficulty: "Avanzada",
    question: "Un suplente del equipo atacante entra sin permiso, interfiere y su equipo marca inmediatamente. ¿Qué decisión corresponde?",
    options: ["Conceder el gol y amonestar", "Anular el gol, amonestar y tiro libre directo", "Anular el gol y balón a tierra", "Conceder el gol si no tocó el balón"],
    correct: 1,
    explanation: "La interferencia de un suplente del equipo que marca invalida el gol.",
    ifabExplanation: "La Regla 3 dispone que, si una persona adicional vinculada al equipo que marca interfiere, el gol se anula. El suplente es amonestado por ingresar sin permiso y el juego se reanuda con tiro libre directo desde el lugar de la interferencia.",
  },
  {
    id: 6,
    topic: "Regla 3",
    lawReference: "Regla 3 - Los jugadores",
    difficulty: "Media",
    question: "Un equipo queda con seis jugadores porque uno abandona deliberadamente el campo. ¿Puede el árbitro permitir que el juego continúe?",
    options: ["Sí, hasta la siguiente interrupción", "Sí, si va ganando", "No, el partido no puede continuar", "Solo durante cinco minutos"],
    correct: 2,
    explanation: "Un equipo no puede continuar con menos de siete jugadores.",
    ifabExplanation: "La Regla 3 fija un mínimo de siete jugadores. Si un jugador abandona deliberadamente, el árbitro puede aplicar ventaja mientras el balón está en juego, pero debe detenerlo cuando salga y no puede reanudar si el equipo sigue con menos de siete.",
  },
  {
    id: 7,
    topic: "Regla 4",
    lawReference: "Regla 4 - El equipamiento de los jugadores",
    difficulty: "Media",
    question: "Un jugador intenta cubrir un anillo con cinta para poder jugar. ¿Qué debe decidir el árbitro?",
    options: ["Permitirlo si queda totalmente cubierto", "Ordenar que retire el anillo", "Permitirlo solo al capitán", "Amonestarlo y permitirle continuar"],
    correct: 1,
    explanation: "Las joyas están prohibidas y no pueden cubrirse con cinta.",
    ifabExplanation: "La Regla 4 exige retirar todo elemento de joyería peligroso. Cubrirlo con cinta no convierte el objeto en seguro ni satisface la Regla.",
  },
  {
    id: 8,
    topic: "Regla 4",
    lawReference: "Regla 4 - El equipamiento de los jugadores",
    difficulty: "Avanzada",
    question: "Un jugador al que se ordenó corregir su equipamiento vuelve al campo sin autorización. ¿Qué corresponde?",
    options: ["Nada si ya corrigió el problema", "Amonestación y salida en la siguiente interrupción si el equipo no obtiene ventaja", "Expulsión directa", "Tiro libre directo siempre"],
    correct: 1,
    explanation: "El reingreso sin permiso es una conducta amonestable.",
    ifabExplanation: "La Regla 4 requiere autorización del árbitro para reingresar luego de corregir el equipamiento. El jugador debe ser amonestado; si el juego se detiene exclusivamente por esta infracción, la reanudación es tiro libre indirecto.",
  },
  {
    id: 9,
    topic: "Regla 5",
    lawReference: "Regla 5 - El árbitro",
    difficulty: "Avanzada",
    question: "El árbitro advierte que su decisión fue incorrecta después de que el juego ya se reanudó. Fuera de las excepciones del protocolo VAR, ¿puede cambiarla?",
    options: ["Sí, en cualquier momento", "Sí, si lo pide el asistente", "No", "Solo antes del descanso"],
    correct: 2,
    explanation: "Una decisión no puede cambiarse después de la reanudación, salvo excepciones expresas.",
    ifabExplanation: "La Regla 5 protege la continuidad del partido: una vez reanudado el juego, el árbitro no puede modificar la decisión de la interrupción anterior, excepto los casos limitados previstos por el protocolo VAR.",
  },
  {
    id: 10,
    topic: "Regla 5",
    lawReference: "Regla 5 - El árbitro",
    difficulty: "Media",
    question: "¿Quién tiene la decisión final sobre todos los hechos relacionados con el juego?",
    options: ["El cuarto árbitro", "El VAR", "El árbitro", "El delegado del partido"],
    correct: 2,
    explanation: "El árbitro es la autoridad final del partido.",
    ifabExplanation: "La Regla 5 establece que las decisiones del árbitro sobre hechos del juego son definitivas. Los demás oficiales, incluido el VAR, asisten bajo su control y dirección.",
  },
  {
    id: 11,
    topic: "Regla 6",
    lawReference: "Regla 6 - Los otros miembros del equipo arbitral",
    difficulty: "Media",
    question: "El árbitro asistente señala fuera de juego, pero el árbitro considera que no hubo infracción. ¿Quién decide?",
    options: ["El asistente", "El cuarto árbitro", "El árbitro", "El capitán defensor"],
    correct: 2,
    explanation: "Las indicaciones de los otros oficiales son asesoramiento.",
    ifabExplanation: "La Regla 6 define funciones de asistencia, pero todos los oficiales actúan bajo la dirección del árbitro, quien conserva la decisión final.",
  },
  {
    id: 12,
    topic: "Regla 6",
    lawReference: "Regla 6 - Los otros miembros del equipo arbitral",
    difficulty: "Avanzada",
    question: "¿Cuál es una responsabilidad propia del cuarto árbitro?",
    options: ["Decidir todos los penales", "Supervisar el área técnica y el procedimiento de sustituciones", "Revisar imágenes VAR", "Controlar exclusivamente la línea de meta"],
    correct: 1,
    explanation: "El cuarto árbitro asiste dentro y fuera del terreno.",
    ifabExplanation: "La Regla 6 y el glosario IFAB asignan al cuarto árbitro tareas como supervisar el área técnica, controlar suplentes y asistir al árbitro en asuntos del partido.",
  },
  {
    id: 13,
    topic: "Regla 7",
    lawReference: "Regla 7 - La duración del partido",
    difficulty: "Media",
    question: "¿Cuál de estas situaciones debe incluirse al calcular el tiempo adicional?",
    options: ["Solo lesiones graves", "Sustituciones, sanciones, celebraciones y revisiones VAR", "Solo pérdidas deliberadas", "Únicamente el tiempo indicado por el cuarto árbitro"],
    correct: 1,
    explanation: "El árbitro recupera todo tiempo perdido relevante.",
    ifabExplanation: "La Regla 7 enumera, entre otras causas, sustituciones, evaluación o retirada de lesionados, medidas disciplinarias, celebraciones, demoras y chequeos o revisiones VAR.",
  },
  {
    id: 14,
    topic: "Regla 7",
    lawReference: "Regla 7 - La duración del partido",
    difficulty: "Avanzada",
    question: "El árbitro comete un error de cronometraje en el primer tiempo. ¿Puede alterar la duración del segundo para compensarlo?",
    options: ["Sí", "Solo con acuerdo de ambos equipos", "No", "Solo en competiciones sin VAR"],
    correct: 2,
    explanation: "Cada periodo debe gestionarse conforme a su propia duración.",
    ifabExplanation: "La Regla 7 no permite compensar un error de cronometraje de un periodo modificando la duración del otro.",
  },
  {
    id: 15,
    topic: "Regla 8",
    lawReference: "Regla 8 - Inicio y reanudación del juego",
    difficulty: "Avanzada",
    question: "El árbitro detiene el juego fuera del área penal sin infracción. El último toque fue de un defensor. ¿A quién se entrega el balón a tierra?",
    options: ["Al equipo atacante", "Al equipo defensor, que fue el último en tocarlo", "A un jugador de cada equipo", "Al guardameta defensor"],
    correct: 1,
    explanation: "Fuera del área penal, se entrega al equipo que tocó el balón por última vez.",
    ifabExplanation: "La Regla 8 concede el balón a tierra a un jugador del equipo que tuvo el último contacto, en el punto correspondiente; los demás jugadores deben permanecer al menos a cuatro metros.",
  },
  {
    id: 16,
    topic: "Regla 8",
    lawReference: "Regla 8 - Inicio y reanudación del juego",
    difficulty: "Avanzada",
    question: "Tras un balón a tierra, el ejecutante remata directamente al arco rival sin que otro jugador toque el balón y convierte. ¿Cómo se reanuda?",
    options: ["Gol", "Saque de meta", "Repetir balón a tierra", "Tiro libre indirecto"],
    correct: 1,
    explanation: "No puede marcarse directamente desde balón a tierra sin un segundo toque de jugador.",
    ifabExplanation: "La Regla 8 exige que el balón toque al menos a dos jugadores antes de un gol. Si entra directamente en la portería rival, se concede saque de meta.",
  },
  {
    id: 17,
    topic: "Regla 9",
    lawReference: "Regla 9 - Balón en juego y fuera de juego",
    difficulty: "Media",
    question: "El balón toca al árbitro, permanece en el campo y cambia la posesión de un equipo al otro. ¿Qué corresponde?",
    options: ["Seguir siempre", "Balón a tierra", "Tiro libre indirecto", "Saque de banda"],
    correct: 1,
    explanation: "Ese contacto genera una de las consecuencias que obligan a detener.",
    ifabExplanation: "La Regla 9 ordena balón a tierra cuando el balón toca a un oficial, permanece en el terreno y cambia la posesión, inicia un ataque prometedor o entra directamente en la portería.",
  },
  {
    id: 18,
    topic: "Regla 9",
    lawReference: "Regla 9 - Balón en juego y fuera de juego",
    difficulty: "Avanzada",
    question: "El balón toca al árbitro, sigue en el campo y no cambia la posesión ni inicia un ataque prometedor. ¿Qué debe hacer el árbitro?",
    options: ["Detener y balón a tierra", "Seguir el juego", "Tiro libre indirecto", "Repetir la acción anterior"],
    correct: 1,
    explanation: "No todo contacto con el árbitro obliga a detener.",
    ifabExplanation: "Si no ocurre ninguna de las consecuencias específicas de la Regla 9, el balón sigue en juego aunque haya tocado a un miembro del equipo arbitral.",
  },
  {
    id: 19,
    topic: "Regla 10",
    lawReference: "Regla 10 - Determinación del resultado de un partido",
    difficulty: "Avanzada",
    question: "Antes de una tanda de penales un equipo tiene más jugadores elegibles que el rival. ¿Qué debe hacer?",
    options: ["Mantenerlos y lanzar con ventaja", "Reducir su número para igualar al rival", "El rival agrega suplentes", "El árbitro elige quién no lanza"],
    correct: 1,
    explanation: "Los equipos deben comenzar la tanda con igual cantidad de jugadores elegibles.",
    ifabExplanation: "La Regla 10 obliga al equipo con mayor número a excluir jugadores hasta igualar al adversario e informar al árbitro sus nombres y dorsales.",
  },
  {
    id: 20,
    topic: "Regla 10",
    lawReference: "Regla 10 - Determinación del resultado de un partido",
    difficulty: "Avanzada",
    question: "Un jugador fue amonestado durante el partido y luego recibe una amonestación durante la tanda. ¿Se considera expulsado por doble amonestación?",
    options: ["Sí", "No, las amonestaciones del partido no se trasladan a la tanda", "Solo si es capitán", "Depende del resultado"],
    correct: 1,
    explanation: "Las amonestaciones del partido no se trasladan a la tanda.",
    ifabExplanation: "La Regla 10 indica que las amonestaciones recibidas durante el partido no se arrastran a la tanda. Las sanciones que ocurran dentro de la tanda se computan según su propio procedimiento.",
  },
  {
    id: 21,
    topic: "Regla 11",
    lawReference: "Regla 11 - Fuera de juego",
    difficulty: "Avanzada",
    question: "Un defensor realiza una salvada deliberada y el rebote llega a un atacante que estaba en posición de fuera de juego cuando su compañero jugó el balón. ¿Qué corresponde?",
    options: ["Seguir por juego deliberado del defensor", "Fuera de juego", "Balón a tierra", "Tiro libre directo"],
    correct: 1,
    explanation: "Una salvada deliberada no habilita al atacante.",
    ifabExplanation: "La Regla 11 diferencia el juego deliberado de una salvada deliberada. Recibir el balón tras una salvada no elimina la infracción por ganar ventaja de la posición de fuera de juego.",
  },
  {
    id: 22,
    topic: "Regla 11",
    lawReference: "Regla 11 - Fuera de juego",
    difficulty: "Media",
    question: "Un atacante en posición de fuera de juego bloquea claramente la línea de visión del guardameta cuando un compañero remata. ¿Qué corresponde?",
    options: ["Seguir porque no toca el balón", "Fuera de juego por interferir con un adversario", "Tiro libre directo", "Balón a tierra"],
    correct: 1,
    explanation: "Bloquear claramente la visión es interferir con un adversario.",
    ifabExplanation: "La Regla 11 sanciona al jugador en posición de fuera de juego que impide que un adversario juegue o pueda jugar el balón al obstruir claramente su línea de visión.",
  },
  {
    id: 23,
    topic: "Regla 12",
    lawReference: "Regla 12 - Faltas y conducta incorrecta",
    difficulty: "Media",
    question: "Una entrada se realiza con desprecio por el peligro o las consecuencias para el adversario. ¿Cómo la define IFAB y qué sanción disciplinaria exige?",
    options: ["Imprudente, sin tarjeta", "Temeraria, amonestación", "Fuerza excesiva, advertencia", "Conducta violenta, expulsión siempre"],
    correct: 1,
    explanation: "La acción es temeraria y exige amonestación.",
    ifabExplanation: "La Regla 12 define reckless como actuar ignorando el peligro o las consecuencias para el adversario. Una infracción cometida de manera temeraria debe sancionarse con tarjeta amarilla.",
  },
  {
    id: 24,
    topic: "Regla 12",
    lawReference: "Regla 12 - Faltas y conducta incorrecta",
    difficulty: "Avanzada",
    question: "Un defensor comienza a sujetar a un atacante fuera del área y continúa sujetándolo dentro del área penal. ¿Cuál es la reanudación?",
    options: ["Tiro libre directo fuera del área", "Penal", "Tiro libre indirecto", "Balón a tierra"],
    correct: 1,
    explanation: "La infracción continuada llega al área penal.",
    ifabExplanation: "La Regla 12 establece expresamente que, si la sujeción comienza fuera y continúa dentro del área penal del defensor, se concede un penal.",
  },
  {
    id: 25,
    topic: "Regla 12",
    lawReference: "Regla 12.3 - Control del guardameta",
    difficulty: "Avanzada",
    question: "En 2025/26, un guardameta controla el balón con las manos durante más de ocho segundos dentro de su área. ¿Qué reanudación corresponde?",
    options: ["Tiro libre indirecto", "Tiro libre directo", "Saque de esquina", "Balón a tierra"],
    correct: 2,
    explanation: "La sanción reglamentaria 2025/26 es saque de esquina.",
    ifabExplanation: "La Regla 12.3 de 2025/26 dispone saque de esquina si el guardameta retiene el balón con manos o brazos más de ocho segundos. El árbitro cuenta visualmente los últimos cinco segundos.",
  },
  {
    id: 26,
    topic: "Regla 12",
    lawReference: "Regla 12 - DOGSO y sanción disciplinaria",
    difficulty: "Avanzada",
    question: "Un defensor comete dentro de su área una infracción DOGSO al intentar jugar o disputar el balón y se concede penal. ¿Qué sanción disciplinaria corresponde?",
    options: ["Sin tarjeta", "Amonestación", "Expulsión en todos los casos", "Solo advertencia"],
    correct: 1,
    explanation: "La tentativa genuina de jugar o disputar el balón reduce la sanción a amarilla.",
    ifabExplanation: "Cuando se concede penal por DOGSO y la infracción fue un intento de jugar o una disputa por el balón, la Regla 12 establece amonestación. La reducción no se aplica a sujeción, empujón, mano deliberada u otras acciones sin posibilidad de jugar el balón.",
  },
  {
    id: 27,
    topic: "Regla 13",
    lawReference: "Regla 13 - Tiros libres",
    difficulty: "Media",
    question: "¿Cuándo está en juego el balón en un tiro libre?",
    options: ["Cuando el árbitro baja el brazo", "Cuando es pateado y se mueve claramente", "Cuando sale del área", "Cuando lo toca un segundo jugador"],
    correct: 1,
    explanation: "El balón debe ser pateado y moverse claramente.",
    ifabExplanation: "La Regla 13 determina que el balón entra en juego cuando ha sido pateado y se mueve claramente, salvo las condiciones adicionales que puedan corresponder al lugar de ejecución.",
  },
  {
    id: 28,
    topic: "Regla 13",
    lawReference: "Regla 13 - Barrera defensiva",
    difficulty: "Avanzada",
    question: "En un tiro libre, tres defensores forman una barrera. Un atacante se coloca a menos de un metro de ella cuando se ejecuta. ¿Cómo se sanciona?",
    options: ["Tiro libre directo para la defensa", "Tiro libre indirecto para la defensa", "Repetición sin sanción", "Seguir siempre"],
    correct: 1,
    explanation: "El atacante debe permanecer al menos a un metro de una barrera de tres o más defensores.",
    ifabExplanation: "La Regla 13 exige esa distancia. Si el atacante la infringe cuando se ejecuta el tiro libre, se concede tiro libre indirecto al equipo defensor.",
  },
  {
    id: 29,
    topic: "Regla 14",
    lawReference: "Regla 14 - El penal",
    difficulty: "Avanzada",
    question: "El ejecutor completa la carrera, hace una finta ilegal al rematar y convierte. ¿Qué corresponde?",
    options: ["Gol", "Repetición y advertencia", "Tiro libre indirecto y amonestación al ejecutor", "Saque de meta"],
    correct: 2,
    explanation: "La finta una vez completada la carrera es una infracción del ejecutor.",
    ifabExplanation: "La Regla 14 permite fintas durante la carrera, pero no una vez completada. El ejecutor es amonestado y se concede tiro libre indirecto, independientemente de que el balón entre.",
  },
  {
    id: 30,
    topic: "Regla 14",
    lawReference: "Regla 14 - El penal",
    difficulty: "Avanzada",
    question: "Ejecutor y guardameta infringen simultáneamente durante un penal y el balón entra. ¿Qué decisión corresponde?",
    options: ["Gol", "Repetición y amonestación a ambos", "Tiro libre indirecto y amonestación al ejecutor", "Saque de meta"],
    correct: 2,
    explanation: "La infracción del ejecutor prevalece en la infracción simultánea.",
    ifabExplanation: "La Regla 14 dispone que, ante infracción simultánea de guardameta y ejecutor, se amonesta al ejecutor y se reanuda con tiro libre indirecto para la defensa.",
  },
  {
    id: 31,
    topic: "Regla 15",
    lawReference: "Regla 15 - El saque de banda",
    difficulty: "Media",
    question: "Un saque de banda entra directamente en la portería adversaria. ¿Qué corresponde?",
    options: ["Gol", "Saque de meta", "Repetición", "Tiro libre indirecto"],
    correct: 1,
    explanation: "No puede marcarse gol directamente desde un saque de banda.",
    ifabExplanation: "La Regla 15 establece saque de meta si el balón entra directamente en la portería adversaria, y saque de esquina si entra directamente en la propia.",
  },
  {
    id: 32,
    topic: "Regla 15",
    lawReference: "Regla 15 - El saque de banda",
    difficulty: "Avanzada",
    question: "Un adversario se coloca a menos de dos metros y distrae de forma antirreglamentaria al ejecutor. El saque ya fue realizado. ¿Qué corresponde?",
    options: ["Seguir", "Amonestación y tiro libre indirecto", "Expulsión y tiro libre directo", "Repetir sin sanción"],
    correct: 1,
    explanation: "La distracción antirreglamentaria es conducta antideportiva.",
    ifabExplanation: "La Regla 15 exige dos metros de distancia y prohíbe distraer u obstaculizar injustamente. Si el saque fue ejecutado, se amonesta al infractor y se concede tiro libre indirecto.",
  },
  {
    id: 33,
    topic: "Regla 16",
    lawReference: "Regla 16 - El saque de meta",
    difficulty: "Media",
    question: "¿Cuándo entra en juego el balón en un saque de meta?",
    options: ["Cuando sale del área penal", "Cuando es pateado y se mueve claramente", "Cuando lo toca un adversario", "Cuando el árbitro da una segunda señal"],
    correct: 1,
    explanation: "Ya no es necesario que el balón salga del área penal.",
    ifabExplanation: "La Regla 16 establece que el balón está en juego cuando es pateado y se mueve claramente. Los adversarios deben permanecer fuera del área hasta ese momento.",
  },
  {
    id: 34,
    topic: "Regla 16",
    lawReference: "Regla 16 - El saque de meta",
    difficulty: "Avanzada",
    question: "El ejecutor de un saque de meta toca por segunda vez el balón con el pie antes de que lo juegue otro futbolista. ¿Qué corresponde?",
    options: ["Seguir", "Tiro libre indirecto", "Repetir el saque", "Balón a tierra"],
    correct: 1,
    explanation: "Existe una infracción por segundo toque.",
    ifabExplanation: "La Regla 16 sanciona el segundo toque del ejecutor con tiro libre indirecto, salvo que ese segundo contacto constituya una mano sancionable, caso en el que se aplican las disposiciones de tiro libre directo o penal.",
  },
  {
    id: 35,
    topic: "Regla 17",
    lawReference: "Regla 17 - El saque de esquina",
    difficulty: "Media",
    question: "El ejecutor marca directamente en la portería adversaria desde un saque de esquina. ¿Qué corresponde?",
    options: ["Gol", "Saque de meta", "Repetición", "Tiro libre indirecto"],
    correct: 0,
    explanation: "Puede marcarse gol directamente en la portería adversaria.",
    ifabExplanation: "La Regla 17 permite un gol directo desde saque de esquina únicamente contra el equipo adversario.",
  },
  {
    id: 36,
    topic: "Regla 17",
    lawReference: "Regla 17 - El saque de esquina",
    difficulty: "Avanzada",
    question: "Un saque de esquina entra directamente en la propia portería del ejecutor. ¿Cómo se reanuda?",
    options: ["Gol en contra", "Saque de meta", "Saque de esquina para el adversario", "Repetición"],
    correct: 2,
    explanation: "No puede marcarse un autogol directamente desde un saque de esquina.",
    ifabExplanation: "La Regla 17 establece que, si el balón entra directamente en la propia portería, se concede saque de esquina al equipo adversario.",
  },
  {
    id: 37,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - Principios",
    difficulty: "Media",
    question: "¿Cuáles son las cuatro categorías revisables por VAR?",
    options: ["Todo tiro libre, toda amarilla, goles y laterales", "Gol/no gol, penal/no penal, roja directa e identidad equivocada", "Fueras de juego, córners, saques de banda y faltas", "Solo goles y penales"],
    correct: 1,
    explanation: "El protocolo limita la asistencia VAR a cuatro categorías decisivas.",
    ifabExplanation: "El VAR puede intervenir por error claro y obvio o incidente grave omitido únicamente en gol/no gol, penal/no penal, tarjeta roja directa y confusión de identidad.",
  },
  {
    id: 38,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - Decisión original",
    difficulty: "Avanzada",
    question: "¿Puede el árbitro indicar que no toma ninguna decisión y pedir al VAR que decida por él?",
    options: ["Sí", "Solo en penales", "No", "Solo si el VAR lo solicita"],
    correct: 2,
    explanation: "El árbitro debe tomar siempre una decisión inicial.",
    ifabExplanation: "El protocolo exige arbitrar como si no existiera VAR. Permitir continuar también constituye una decisión revisable; el VAR asiste, pero no sustituye la decisión inicial ni final del árbitro.",
  },
  {
    id: 39,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - Check y review",
    difficulty: "Avanzada",
    question: "Para valorar la intensidad de una entrada o decidir si un contacto de mano es sancionable, ¿qué velocidad de repetición debe priorizarse?",
    options: ["Cámara lenta", "Velocidad normal", "Imagen congelada", "Cualquier velocidad es equivalente"],
    correct: 1,
    explanation: "La velocidad normal preserva la lectura real de intensidad y movimiento.",
    ifabExplanation: "El protocolo reserva, en general, la cámara lenta para hechos como punto de contacto, posición o balón fuera. La intensidad de una acción y la valoración global de una mano deben analizarse principalmente a velocidad normal.",
  },
  {
    id: 40,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - OFR y revisión solo VAR",
    difficulty: "Avanzada",
    question: "Una posible mano sancionable exige una valoración subjetiva sobre posición y movimiento del brazo. ¿Qué tipo de revisión es normalmente apropiada?",
    options: ["Revisión solo VAR", "On-field review (OFR)", "No puede revisarse", "Decisión del operador de repeticiones"],
    correct: 1,
    explanation: "Las decisiones subjetivas requieren normalmente una revisión en campo.",
    ifabExplanation: "El protocolo indica OFR para decisiones subjetivas como intensidad, interferencia en fuera de juego o consideraciones de mano. Las decisiones puramente factuales suelen resolverse con revisión solo VAR.",
  },
  {
    id: 41,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - Categorías revisables",
    difficulty: "Media",
    question: "El árbitro no observa una infracción que habría supuesto una segunda amonestación. ¿Puede el VAR recomendar una revisión exclusivamente por ese motivo?",
    options: ["Sí", "No", "Solo si ocurre dentro del área", "Solo en tiempo adicional"],
    correct: 1,
    explanation: "La segunda amonestación no es una categoría revisable.",
    ifabExplanation: "El protocolo incluye tarjetas rojas directas, pero excluye expresamente la segunda tarjeta amarilla como categoría autónoma de intervención VAR.",
  },
  {
    id: 42,
    topic: "VAR",
    lawReference: "Protocolo VAR 2025/26 - Juego ya reanudado",
    difficulty: "Avanzada",
    question: "Después de una reanudación, ¿en cuál de estos casos todavía puede iniciarse una revisión?",
    options: ["Un saque de banda mal concedido", "Una posible conducta violenta no observada", "Una falta táctica sin tarjeta", "Un córner otorgado por error"],
    correct: 1,
    explanation: "Luego de reanudar solo subsisten excepciones muy limitadas.",
    ifabExplanation: "Tras la reanudación, el protocolo solo permite revisión por identidad equivocada o una posible expulsión relacionada con conducta violenta, escupir, morder o acciones extremadamente ofensivas, insultantes o abusivas.",
  },
];
